server:
  port: 8002

spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/shortlink?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 20
      minimum-idle: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 12345